/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'AC Infinity Adapter Settings': {
        'en': 'AC Infinity Adapter Settings',
        'de': 'AC Infinity Adapter Einstellungen',
        'ru': 'Настройки адаптера AC Infinity',
        'pt': 'Configurações do adaptador AC Infinity',
        'nl': 'AC Infinity Adapter Instellingen',
        'fr': 'Paramètres de l\'adaptateur AC Infinity',
        'it': 'Impostazioni adattatore AC Infinity',
        'es': 'Configuración del adaptador AC Infinity',
        'pl': 'Ustawienia adaptera AC Infinity',
        'uk': 'Налаштування адаптера AC Infinity',
        'zh-cn': 'AC Infinity 适配器设置'
    },
    'AC Infinity Email': {
        'en': 'AC Infinity Email',
        'de': 'AC Infinity E-Mail',
        'ru': 'Электронная почта AC Infinity',
        'pt': 'E-mail AC Infinity',
        'nl': 'AC Infinity E-mail',
        'fr': 'E-mail AC Infinity',
        'it': 'Email AC Infinity',
        'es': 'Correo electrónico AC Infinity',
        'pl': 'Email AC Infinity',
        'uk': 'Електронна пошта AC Infinity',
        'zh-cn': 'AC Infinity 电子邮箱'
    },
    'Email address used for AC Infinity login': {
        'en': 'Email address used for AC Infinity login',
        'de': 'E-Mail-Adresse für AC Infinity Login',
        'ru': 'Адрес электронной почты для входа в AC Infinity',
        'pt': 'Endereço de e-mail usado para login no AC Infinity',
        'nl': 'E-mailadres gebruikt voor AC Infinity login',
        'fr': 'Adresse e-mail utilisée pour la connexion AC Infinity',
        'it': 'Indirizzo email utilizzato per l\'accesso AC Infinity',
        'es': 'Dirección de correo electrónico utilizada para iniciar sesión en AC Infinity',
        'pl': 'Adres e-mail używany do logowania AC Infinity',
        'uk': 'Електронна адреса для входу в AC Infinity',
        'zh-cn': '用于 AC Infinity 登录的电子邮件地址'
    },
    'AC Infinity Password': {
        'en': 'AC Infinity Password',
        'de': 'AC Infinity Passwort',
        'ru': 'Пароль AC Infinity',
        'pt': 'Senha AC Infinity',
        'nl': 'AC Infinity Wachtwoord',
        'fr': 'Mot de passe AC Infinity',
        'it': 'Password AC Infinity',
        'es': 'Contraseña AC Infinity',
        'pl': 'Hasło AC Infinity',
        'uk': 'Пароль AC Infinity',
        'zh-cn': 'AC Infinity 密码'
    },
    'Password used for AC Infinity login': {
        'en': 'Password used for AC Infinity login',
        'de': 'Passwort für AC Infinity Login',
        'ru': 'Пароль для входа в AC Infinity',
        'pt': 'Senha usada para login no AC Infinity',
        'nl': 'Wachtwoord gebruikt voor AC Infinity login',
        'fr': 'Mot de passe utilisé pour la connexion AC Infinity',
        'it': 'Password utilizzata per l\'accesso AC Infinity',
        'es': 'Contraseña utilizada para iniciar sesión en AC Infinity',
        'pl': 'Hasło używane do logowania AC Infinity',
        'uk': 'Пароль для входу в AC Infinity',
        'zh-cn': '用于 AC Infinity 登录的密码'
    },
    'Polling Interval (seconds)': {
        'en': 'Polling Interval (seconds)',
        'de': 'Abfrageintervall (Sekunden)',
        'ru': 'Интервал опроса (секунды)',
        'pt': 'Intervalo de sondagem (segundos)',
        'nl': 'Polling interval (seconden)',
        'fr': 'Intervalle de sondage (secondes)',
        'it': 'Intervallo di polling (secondi)',
        'es': 'Intervalo de sondeo (segundos)',
        'pl': 'Interwał odpytywania (sekundy)',
        'uk': 'Інтервал опитування (секунди)',
        'zh-cn': '轮询间隔（秒）'
    },
    'Minimum polling interval is 5 seconds.': {
        'en': 'Minimum polling interval is 5 seconds.',
        'de': 'Minimales Abfrageintervall beträgt 5 Sekunden.',
        'ru': 'Минимальный интервал опроса составляет 5 секунд.',
        'pt': 'O intervalo mínimo de sondagem é de 5 segundos.',
        'nl': 'Minimale polling interval is 5 seconden.',
        'fr': 'L\'intervalle de sondage minimum est de 5 secondes.',
        'it': 'L\'intervallo minimo di polling è di 5 secondi.',
        'es': 'El intervalo mínimo de sondeo es de 5 segundos.',
        'pl': 'Minimalny interwał odpytywania wynosi 5 sekund.',
        'uk': 'Мінімальний інтервал опитування становить 5 секунд.',
        'zh-cn': '最小轮询间隔为 5 秒。'
    },
    'Note: AC Infinity truncates passwords to 25 characters.': {
        'en': 'Note: AC Infinity truncates passwords to 25 characters.',
        'de': 'Hinweis: AC Infinity kürzt Passwörter auf 25 Zeichen.',
        'ru': 'Примечание: AC Infinity сокращает пароли до 25 символов.',
        'pt': 'Nota: AC Infinity trunca senhas para 25 caracteres.',
        'nl': 'Opmerking: AC Infinity verkort wachtwoorden tot 25 tekens.',
        'fr': 'Remarque: AC Infinity tronque les mots de passe à 25 caractères.',
        'it': 'Nota: AC Infinity tronca le password a 25 caratteri.',
        'es': 'Nota: AC Infinity trunca las contraseñas a 25 caracteres.',
        'pl': 'Uwaga: AC Infinity skraca hasła do 25 znaków.',
        'uk': 'Примітка: AC Infinity скорочує паролі до 25 символів.',
        'zh-cn': '注意：AC Infinity 将密码截断为 25 个字符。'
    },
    // Zusätzliche Begriffe, die möglicherweise im Interface verwendet werden
    'WARNING / WARNUNG': {
        'en': 'WARNING',
        'de': 'WARNUNG',
        'ru': 'ПРЕДУПРЕЖДЕНИЕ',
        'pt': 'AVISO',
        'nl': 'WAARSCHUWING',
        'fr': 'AVERTISSEMENT',
        'it': 'AVVERTENZA',
        'es': 'ADVERTENCIA',
        'pl': 'OSTRZEŻENIE',
        'uk': 'ПОПЕРЕДЖЕННЯ',
        'zh-cn': '警告'
    },
    'This adapter is in an early development stage. You use this adapter at your own risk. The author assumes no liability for any damage.': {
        'en': 'This adapter is in an early development stage. You use this adapter at your own risk. The author assumes no liability for any damage.',
        'de': 'Dieser Adapter befindet sich in einem frühen Entwicklungsstadium. Sie verwenden diesen Adapter auf eigene Gefahr. Der Autor übernimmt keine Haftung für eventuelle Schäden.',
        'ru': 'Этот адаптер находится на ранней стадии разработки. Вы используете этот адаптер на свой страх и риск. Автор не несет ответственности за возможный ущерб.',
        'pt': 'Este adaptador está em um estágio inicial de desenvolvimento. Você usa este adaptador por sua conta e risco. O autor não assume nenhuma responsabilidade por quaisquer danos.',
        'nl': 'Deze adapter bevindt zich in een vroeg ontwikkelingsstadium. U gebruikt deze adapter op eigen risico. De auteur aanvaardt geen aansprakelijkheid voor eventuele schade.',
        'fr': 'Cet adaptateur est à un stade précoce de développement. Vous utilisez cet adaptateur à vos propres risques. L\'auteur n\'assume aucune responsabilité pour tout dommage.',
        'it': 'Questo adattatore è in una fase iniziale di sviluppo. Usi questo adattatore a tuo rischio e pericolo. L\'autore non si assume alcuna responsabilità per eventuali danni.',
        'es': 'Este adaptador está en una etapa temprana de desarrollo. Utiliza este adaptador bajo tu propio riesgo. El autor no asume ninguna responsabilidad por cualquier daño.',
        'pl': 'Ten adapter jest we wczesnej fazie rozwoju. Korzystasz z tego adaptera na własne ryzyko. Autor nie ponosi odpowiedzialności za jakiekolwiek szkody.',
        'uk': 'Цей адаптер знаходиться на ранній стадії розробки. Ви використовуєте цей адаптер на власний ризик. Автор не несе відповідальності за будь-які збитки.',
        'zh-cn': '此适配器处于早期开发阶段。使用此适配器的风险由您自行承担。作者不承担任何损害赔偿责任。'
    },
    'Polling Interval / Abfrageintervall (seconds)': {
        'en': 'Polling Interval (seconds)',
        'de': 'Abfrageintervall (Sekunden)',
        'ru': 'Интервал опроса (секунды)',
        'pt': 'Intervalo de sondagem (segundos)',
        'nl': 'Polling interval (seconden)',
        'fr': 'Intervalle de sondage (secondes)',
        'it': 'Intervallo di polling (secondi)',
        'es': 'Intervalo de sondeo (segundos)',
        'pl': 'Interwał odpytywania (sekundy)',
        'uk': 'Інтервал опитування (секунди)',
        'zh-cn': '轮询间隔（秒）'
    },
    'AC Infinity Password / Passwort': {
        'en': 'AC Infinity Password',
        'de': 'AC Infinity Passwort',
        'ru': 'Пароль AC Infinity',
        'pt': 'Senha AC Infinity',
        'nl': 'AC Infinity Wachtwoord',
        'fr': 'Mot de passe AC Infinity',
        'it': 'Password AC Infinity',
        'es': 'Contraseña AC Infinity',
        'pl': 'Hasło AC Infinity',
        'uk': 'Пароль AC Infinity',
        'zh-cn': 'AC Infinity 密码'
    }
};